name: C/C++ CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Compilar potencia
      run: gcc potencia.c -o potencia

    - name: Executar potencia com argumentos
      run: ./potencia 5 2

    - name: Mostrar o conteudo do arquivo criado
      run: cat potencia.txt

    - name: Compilar testes
      run: gcc testes.c -o testes

    - name: Executar testes
      run: ./testes
